In [3]:
from tabulate import tabulate
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from matplotlib.backends.backend_pdf import PdfPages
from datetime import datetime
today = datetime.today().strftime("%Y-%m-%d")

#Stats Import
from scipy.stats import wilcoxon 
import pingouin as pg
from pingouin import pairwise_ttests, pairwise_tukey, pairwise_gameshowell
import statsmodels.stats.multicomp as mc
import scipy.stats as stats
import statsmodels.api as sm
from bioinfokit.analys import stat

sys.path.append(os.path.join(sys.path[0],'U:\lamb_consulting'))
# import cox, means, regressions

from lamb_consulting import *

from lamb_consulting.means import means_desc, means_desc_class, aov
from lamb_consulting.freqs import freqs, chi_contingency
from lamb_consulting.export import export_to_Excel
from lamb_consulting.regressions import ols, regression_plot
from lamb_consulting.cox import cox
from lamb_consulting.kaplan_meier import km,km_plots




def freqme(ds,var1):
    f=ds[var1].value_counts(dropna=False)
    p=ds[var1].value_counts(normalize=True)
    df=pd.concat({f,p}, axis=1, keys=['frequency', 'percent'])
    df["cumfrequency"] = df["frequency"].cumsum()
    df["cumpercent"] = df["percent"].cumsum()
    return df

os.getcwd()
tpath = "U:/Fox/Weisse/EHPSS/"
# fn="CanineEHPSSStudy_20221112"
fn="EHPSS20221120"



extension='.xlsx'
file = tpath+fn+extension
file
npl = pd.read_excel((file), sheet_name='data')



# Cntrl 1 Comment Out
# edj.rename(columns = {'SYMBOL/CUSIP':'ticker','SHARES':'vol'}, inplace = True) 
type(npl)
print(npl)

for i in npl.columns:
    print(i)

      pt_num  hospital  country      pid      dob gender_1  gender wt_kgs  \
0          1         0        0  1076523  42685.0       MC       2    3.7
1          2         0        0  1084186  42647.0       FS       4
2          3         0        0   908470  38964.0       FS       4
3          4         0        0   912599  39475.0       FI       3
4          5         0        0  1001546  41025.0       MI       1
...      ...       ...      ...      ...      ...      ...     ...    ...
1077    1078        12        0   250679  40826.0       FS       4    5.7
1078    1079        12        0   344965  42669.0       MC       2    3.2
1079    1080        12        0   347734  43007.0       MI       1    3.5
1080    1081        12        0   335489  42239.0       MI       1    7.9
1081    1082        12        0   353170  41915.0       MC       2    2.2

      ct_dt   age_d              breed_c breed_n  shunt_ty  portal_v  \
0     43029   344.0             Havanese      27         9         4
1     43097   450.0             Shih Tzu      53         1         1
2     40154  1190.0             Shih Tzu      53         1         1
3     40294   819.0                Mixed      38         2         1
4     41128   103.0  Miniature Schnauzer      62         3         1
...     ...     ...                  ...     ...       ...       ...
1077  42838  2012.0              Pug mix      47         2         1
1078  42983   314.0     yorkshire terier      61         5         2
1079  42459  -548.0              maltese      35         4         2
1080  42866   627.0  Miniature schnauzer      62        11         7
1081  43245  1330.0              Maltese      35         4         2

      system_v  contrb_v          pps_c pps_n
0            3       4.0           poor     1
1            1       NaN           Good     5
2            1       NaN           Good     5
3            2       NaN       Moderate     3
4            3       NaN       Moderate     3
...        ...       ...            ...   ...
1077         2       NaN           Good     5
1078         3       2.0           Poor     1
1079         3       1.0           Poor     1
1080         9       NaN  Moderate-Good     4
1081         3       1.0           Good     5

[1082 rows x 18 columns]
pt_num
hospital
country
pid
dob
gender_1
gender
wt_kgs
ct_dt
age_d
breed_c
breed_n
shunt_ty
portal_v
system_v
contrb_v
pps_c
pps_n

In [4]:
# 1) Mean/Median Age (Age_Days)

# 2) Mean/Median Weight (WT_KGS)
# 3) Gender distribution (GENDER) - significant differences?
# 4) Most common Breeds (BREED)
# 5) Most common shunts (SHUNT)
# 6) Most common portal vein origin (PORTAL_V)
# 7) Most common systemic vein insertion (SYSTEM_V)
# 8) Most common contributing vessels (CONTRB_V)
# 9) PP score distribution (PP_Score)

# Cross tab frequencies and ANOVA
# HOSPITAL COMPARISONS (HOSPITAL):
# 10) Do the above values differ AMONG HOSPITALS (HOSPITAL) 

# Cross tab frequencies and ANOVA
# COUNTRY COMPARISONS (COUNTRY):
# 11) Do the above values differ AMONG COUNTRIES (COUNTRY) 

# Cross tab frequencies and ANOVA
# BREED COMPARISONS (BREED): [5 MOST COMMON BREEDS]
# 12) What is Gender distribution (GENDER) comparison among 5 most common breeds (BREED)?
# 13) What is Age distribution (Age_Days) comparison among 5 most common breeds (BREED)?
# 14) What are 5 most common Shunts  (SHUNT) comparison among 5 most common breeds (BREED)?
# 15) What is PP Score (PP_Score) comparison among 5 most common breeds (BREED)?


# Regression and ANOVA
# AGE COMPARISONS (Age_Days):
# 16) Does AGE (Age_Days) correlate with Breed (BREED)
# 17) Does AGE (Age_Days) correlate with PP Score (PP_Score)
# 18) Does AGE (Age_Days) correlate with Shunt (SHUNT)


# SHUNT COMPARISONS (SHUNT) ANOVA:
# 19) Does Shunt (SHUNT) correlate with Weight (WT_KGS)    [Above and below mean/median?]
# 20) Does Shunt (SHUNT) correlate with PP Score (PP_Score)

# Breed ANOVA and Cross Tab
# 21) Does PV origin (PORTAL_V) correlate with breed (BREED)
# 22) Does systemic v insertion (SYSTEM_V) correlate with breed (BREED)
# 23) Do contributing vessels (CONTRB_V) correlate with breed (BREED)


# npl['sex'] = npl['GENDER'].astype(int)


# all_df = all_df.astype({'recall': 'float64', 'ds_size': 'float64'})
# all_df.info()

# all_df['monht_year'] = pd.to_datetime(all_df['dt']).dt.to_period("M")

# all_df['condition'] = ""

# all_df.loc[(all_df['tp'] ==1), "condtion"] = 'tp'

# all_df['gt'] = all_df.xxx.apply(lambda x: 1 if x == "Y" else 0)
# all_df = all_df[all_df.coumns[~all_df.columns.isin(['xxx'])]]


# month_data = []
# gridvars = ['tp', 'tn', 'fn', 'fp']
# for i in time_mo:
#     my_mo = df.loc[(df[month_year] == i)]
#     print(my_mo)
#     print(len(my_mo))
#     df_in = my_modfs = df_in[gridvars].sum
#     dfs = dfs.to_frame()
#     dft = dfs.transpose()
#     dft['tot'] = dft.sum(axis=1)
#     dft['tpfn'] = dft.loc[:,['tp','fn']].sum(axis=1)
#     dft['tpfp'] = dft.loc[:,['tp','fp']].sum(axis=1)
#     dft['fpfn'] = dft.loc[:,['fp','fn']].sum(axis=1)
#     dft['recall'] = dft.tp / dft.tpfn
#     dft['precision'] = dft.tp / dft.tpfn
#     dft['recall'] = dft.tp / dft.tpfp
#     dft['pct_gtc'] = dft.tpfn / dft.tot
#     dft['pct_nsc'] = dft.fpfn / dft.tot
#     dft['month_id'] = i
#     month_data.append(dft)


# month_df.rename(column={0:'tp', 1: 'tn'}, inplace = True)

# df.loc[(df['gt'] == 1) & (df['mod'] == 1), 'tp'] = 1
# df.loc[(df['gt'] == 0) & (df['mod'] == 0), 'tn'] = 1

# df['condition'] = ""
# df.loc[(df['Price'] <=100) & (df['Category']=='A'), "Flag"] = 'X'
# df.loc[(df['tp'] ==1), "condition"] = 'tp'
# df.loc[(df['tn'] ==1), "condition"] = 'tn'


def male_n(row):
    if row["gender"] == 1 or row["gender"] == 2:
        return 1
    elif row["gender"] == 3 or row["gender"] == 4:
        return 0
    else:
        return -1


def male_c(row):
    if row["gender_1"] == 'MC' or row["gender_1"] == 'MI':
        return "M"
    elif row["gender_1"] == 'FS' or row["gender_1"] == 'FI':
        return "F"
    else:
        return "error"


npl['male_n'] = npl.apply(male_n,axis=1)
npl['male_c'] = npl.apply(male_c,axis=1)

cont = ['age_d', 'wt_kgs', 'pp_score']
cat = ['gender_c', 'mal_c', 'breed_c', 'shunt_ty', 'portal_v', 'sysem_v', 'contrb_v', 'hospital', 'country']




# def checkAge(inpAge, minAge):
#     if(inpAge>=minAge):
#         return 'senior'
#     else:
#         return 'fresher'
    
# npl['age_ty']=npl['AGE_DAYS'].apply(checkAge, args=(25,))

 
# Priting data
# print(npl.male_n)
# print(npl.male_c)

# npl['sex'] = npl['GENDER'].astype(str)


# npl['male_c'] = (dataFrame.loc[(dataFrame['Salary']>=100000) & (dataFrame['Age']< 40) & (dataFrame['JOB'].str.startswith('D')),
#                     ['Name','JOB']])
# ['sex'] = npl['GENDER'].astype(int)

In [7]:

npl.info()
print(npl["gender_1"].value_counts())
print(npl["gender"].value_counts())
# print(npl["sex"].value_counts())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1082 entries, 0 to 1081
Data columns (total 20 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pt_num    1082 non-null   int64
 1   hospital  1082 non-null   int64
 2   country   1082 non-null   int64
 3   pid       1082 non-null   object
 4   dob       1082 non-null   float64
 5   gender_1  1082 non-null   object
 6   gender    1082 non-null   int64
 7   wt_kgs    1082 non-null   object
 8   ct_dt     1082 non-null   int64
 9   age_d     1082 non-null   float64
 10  breed_c   1082 non-null   object
 11  breed_n   1082 non-null   object
 12  shunt_ty  1082 non-null   int64
 13  portal_v  1082 non-null   int64
 14  system_v  1082 non-null   int64
 15  contrb_v  363 non-null    float64
 16  pps_c     1082 non-null   object
 17  pps_n     1082 non-null   object
 18  male_n    1082 non-null   int64
 19  male_c    1082 non-null   object
dtypes: float64(3), int64(9), object(8)
memory usage: 169.2+ KB
FS    405
MC    352
FI    169
MI    143
MN      8
M       2
NM      1
FE      1
ME      1
Name: gender_1, dtype: int64
4    405
2    361
3    170
1    146
Name: gender, dtype: int64
F        574
M        495
error     13
Name: male_c, dtype: int64
0    575
1    507
Name: male_n, dtype: int64

In [8]:
print(npl["male_c"].value_counts())
print(npl["male_n"].value_counts())

F        574
M        495
error     13
Name: male_c, dtype: int64
0    575
1    507
Name: male_n, dtype: int64

In [10]:
# cont_describe = cont
# cat_describe = cat
cont_describe = "AGE_DAYS WT_KGS PP_Score"
npl[cont_describe.split(" ")].describe().transpose()
# means_df = means_desc(npl,cont)
# ds[cont_describe.split(" ")].describe().transpose()

,count,mean,std,min,25%,50%,75%,max
AGE_DAYS,1054.0,1108.450664,1057.133359,0.0,295.25,713.0,1648.25,7678.0

In [23]:
npl.sex.value_counts()

4    393
2    354
3    167
1    141
Name: sex, dtype: int64